"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { GlobalStyle } from '@/Themes/Global'
import { ThemeProvider } from 'styled-components'
import { Theme } from '@/Themes/Theme'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={Theme}>
        <body>{children}</body>
        <GlobalStyle />
      </ThemeProvider>
    </html>
  )
}
