"use client"

import type { Metadata } from 'next'
import { Inter, Roboto, Ephesis } from 'next/font/google'

import { GlobalStyle } from '@/Themes/Global'
import { ThemeProvider } from 'styled-components'
import { Theme } from '@/Themes/Theme'

const inter = Inter({ subsets: ['latin'] })
const ephesis = Ephesis({
  weight: "400",
  subsets: ['latin'],
  display: 'swap',
  variable: "--aspas"
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={ephesis.className}>
      <ThemeProvider theme={Theme}>
        <body>{children}</body>
        <GlobalStyle />
      </ThemeProvider>
    </html>
  )
}
